### ISSUE TITLE
EfficientNet B6

### ISSUE THREAD

**Issue by shaunster0** [jkjung-avt/keras_imagenet#3]
hi, thanks for this project!
I’d like to use it with EfficientNet B6, could u outline what would have to be done to make that work? Or it seems it might already support B6, is that so?

Thank u!
Shaun

**Comment by jkjung-avt** [comment]
Sorry I missed this question early on.

Adding EfficientNetB6 is simple, if you'are going to use 224x224 input images (otherwise you'll have to modify my dataset.py code: [here](https://github.com/jkjung-avt/keras_imagenet/blob/master/utils/dataset.py#L81) and [here](https://github.com/jkjung-avt/keras_imagenet/blob/master/utils/dataset.py#L83)).

I have already defined [EfficientNetB6_224x224](https://github.com/jkjung-avt/keras_imagenet/blob/master/models/efficientnet.py#L679) in the code.  To add it into training, you could add the following code into [models.py](https://github.com/jkjung-avt/keras_imagenet/blob/master/models/models.py).

Add this after [line #23](https://github.com/jkjung-avt/keras_imagenet/blob/master/models/models.py#L23):
```
from .efficientnet import EfficientNetB6_224x224
```

And add this after [line #172](https://github.com/jkjung-avt/keras_imagenet/blob/master/models/models.py#L172):
```
            'efficientnet_b6': EfficientNetB6_224x224,
```

And finally you could define the model in train_new.sh, similar to "efficientnet_b0".
